### ISSUE TITLE
Beginner Friendly Issue - Didn't Get Mail Link Broken 

### ISSUE THREAD

**Issue by wimpywarlord** [wimpywarlord/Goodmorning-Girlfriend#1]
Hi,

👉  So I think you found this issue from the Beginner-friendly issues list, and you are just getting started with Open Source.

👉  This is a perfect opportunity to get your hand dirty, and not get overwhelmed at the same time. 

👉 I have deliberately introduced a bug into my website. 

💕 Problem 

The Hyperlink attached to the `Didn't Get Mail`  in the footer is no more working. I want you to prank the user (Rick Roll). Replace the current hyperlink address with the [this](https://www.youtube.com/watch?v=dQw4w9WgXcQ).

Damn you got Rick Rolled as well. 

![Screenshot_8](https://user-images.githubusercontent.com/41532804/135169761-e3b6e52d-2053-4473-8fa4-0706375b9dd0.png)

Kindly help me prank my users 🥺.

💕Assistance

It's under the `client` folder, inside the `src` folder, inside the `views` folder, inside the `index.vue` file.

Search for the `Didn't get mail` anchor tag. 

 💕How to contribute.
 
 Send a PR, and I review it. If it's up to the mark, I will approve it and merge it to the main codebase. 
 
 Learn how to send a PR [here](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

**Comment by Niyati3031** [comment]
@wimpywarlord is this issue categorized under Hacktoberfest 21
If so then assign this to me for Hacktoberfest, i am a complete new to this...

**Comment by wimpywarlord** [comment]
@Niyati3031 Hi Nitya go ahead and send a PR.

**Comment by Niyati3031** [comment]
> @Niyati3031 Hi Nitya go ahead and send a PR.

But I should make pr after 1 october then it will be counted am i right..

**Comment by wimpywarlord** [comment]
Yes, that would be a wise decision.

**Comment by Rajeet10** [comment]
Can u assign me this one as it would help me in getting more confident before hacktoberfest?

**Comment by wimpywarlord** [comment]
Hi @Rajeet10,

Sure you can go ahead and send a PR, since the main objective is to learn the git and open source. 

Assignment holds little value.

Even if your PR doesn't get merged, you will learn the whole process never the less.

Thanks

**Comment by wimpywarlord** [comment]
The issue is been assigned to @satkar2001 and the Raised PR has been merged. The issue is not being closed.
